### ISSUE TITLE
conda install failed

### ISSUE THREAD

**Issue by keyfm** [katholt/srst2#119]
Hi, 

I am trying to install srst2 via `pip install --install-option="--prefix=${HOME}/bin" srst2/ ` but it fails.

The `pip install` finished with `Successfully installed srst2`, however, I get an error when executing `${HOME}/bin/srst2`:

`Traceback (most recent call last):
  File "./srst2", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/cm/shared/c3ddb/python/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/cm/shared/c3ddb/python/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/cm/shared/c3ddb/python/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/cm/shared/c3ddb/python/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/cm/shared/c3ddb/python/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/cm/shared/c3ddb/python/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'srst2==0.2.0' distribution was not found and is required by the application
`

Alternatively I tried installing via `conda install srst2`, which tells me I need to get an older python version:

`UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3
  - srst2 -> python[version='>=2.7,<2.8.0a0']
Use "conda info <package>" to see the dependencies for each package.
`
I am a bit puzzled about this error as I thought it uses python3?

Any advice how to get srst2 running is highly appreciated.

**Comment by katholt** [comment]
SRST2 uses Python 2.7, not compatible with Python 3 (it's on the wishlist to convert, but we don't have the person-power) 
https://github.com/katholt/srst2#installation

**Comment by keyfm** [comment]
thx for the clarification Kat.

I ended up creating a designated srst2 conda environment with py2.7. In case anybody is interested how that was done I paste the code below.

conda create --name srst2 # set up environment called srst2
conda activate srst2 # avtivate
conda install -c bioconda srst2 # install rest2 and dependencies in environment
conda install -c bioconda/label/cf201901 srst2 # -“-

best
f

**Comment by smitha97** [comment]
Thank you for this code patch so much! I couldn't figure out how to bypass the python 3 that was installed on my computer and throwing up errors every time I tried to run the program.
