### ISSUE TITLE
SyntaxError when running srst2

### ISSUE THREAD

**Issue by cpavloud** [katholt/srst2#139]
Hello!
I am trying to run srst2 in an HPC cluster to identify resistance genes and I get the error below: 

_Traceback (most recent call last):
  File "/CCAS/home/cpavloudi/miniconda3/bin/srst2", line 5, in <module>
    from srst2.srst2 import main
  File "/CCAS/home/cpavloudi/miniconda3/lib/python3.9/site-packages/srst2/srst2.py", line 308
    print "Warning! MLST delimiter is " + delimiter + " but these genes may violate the pattern and cause problems:"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Warning! MLST delimiter is " + delimiter + " but these genes may violate the pattern and cause problems:")?_

Do you have any idea why this might be happening?

I checked if I have installed srst2 properly, but maybe something was wrong with my installation?

`(base) srst2 --version`
_Traceback (most recent call last):
  File "/CCAS/home/cpavloudi/miniconda3/bin/srst2", line 5, in <module>
    from srst2.srst2 import main
  File "/CCAS/home/cpavloudi/miniconda3/lib/python3.9/site-packages/srst2/srst2.py", line 308
    print "Warning! MLST delimiter is " + delimiter + " but these genes may violate the pattern and cause problems:"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Warning! MLST delimiter is " + delimiter + " but these genes may violate the pattern and cause problems:")?_

`(base) getmlst.py -h`  
_File "/CCAS/home/cpavloudi/miniconda3/bin/getmlst.py", line 128
    print "No species matched your query."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No species matched your query.")?_

`(base) slurm_srst2.py -h`
  _File "/CCAS/home/cpavloudi/miniconda3/bin/slurm_srst2.py", line 105
    print "Could not determine forward/reverse read status for input file " + fastq
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Could not determine forward/reverse read status for input file " + fastq)?_

**Comment by dannagifford** [comment]
I had this issue too. I solved it by running the scripts with python2, i.e. instead of
getmlst.py -h
run
python2.7 /usr/local/bin/getmlst.py -h
or wherever your scripts were actually installed to.
