### ISSUE TITLE
global name 'seq_id' is not defined error

### ISSUE THREAD

**Issue by AlefNeem** [katholt/srst2#54]
I get this error when I use SRST2, How can I resolve it .

**Comment by katholt** [comment]
Hi Alef, will need a bit more info to help you.
Can you please provide
- version number
- command you are using
- contents of log file
- full text of the error
Thanks

**Comment by AlefNeem** [comment]
Hi
here is the version that I used


  *   command you are using -srst2 --input_pe *.fastq --output strain_serotypeVI__Ant --log --gene_db /home/streplab/Desktop/data_4/Alefiya/SRST_2/database/all_databases.fsa --forward _R1 --reverse _R2
  *   version number-srst2 0.1.2
  *   content oc tther error-0.11% overall alignment rate
[samopen] SAM header is present: 2139 sequences.
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
Traceback (most recent call last):
  File "/usr/local/bin/srst2", line 9, in <module>
    load_entry_point('srst2==0.1.2', 'console_scripts', 'srst2')()
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 1316, in main
    db_reports, db_results = run_srst2(args,fileSets,args.gene_db,"genes")
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 937, in run_srst2
    db_reports, db_results_list = process_fasta_db(args, fileSets, run_type, db_reports, db_results_list, fasta)
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 991, in process_fasta_db
    unique_gene_symbols, unique_allele_symbols,run_type,ST_db,results,gene_list,db_report)
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 1101, in map_fileSet_to_db
    unique_gene_symbols, unique_allele_symbols)
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 679, in parse_scores
    gene_name = get_allele_name_from_db(allele,unique_allele_symbols,unique_cluster_symbols,run_type,args)[0]
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 649, in get_allele_name_from_db
    allele_name += "_" + seq_id
NameError: global name 'seq_id' is not defined


I have attached the log file for you to see. I hope you can help me solve this problem.
thanks

________________________________
