### ISSUE TITLE
file scores_vs_expected.py seems missing

### ISSUE THREAD

**Issue by PWSmit** [katholt/srst2#66]
Hi Kat and others, 

I tried to install srst2 today and run into some issues which seems to be related to missing file called scores_vs_expected.py. using the git clone command, followed by pip install. 

When I copied that file from srst2-0.1.7.zip version and placed in into my directory I got it installed (i.e. it says it got installed). However, the installation is not very successful as, when asking for the current version, it gives out random things (see below). 

Could you please direct me to the right version of that file? 
Many thanks in advance, 

Pieter Smit
 

Traceback (most recent call last):
  File "/usr/local/bin/srst2", line 9, in <module>
    load_entry_point('srst2==0.1.8', 'console_scripts', 'srst2')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/srst2/srst2.py", line 306
    print "Warning! MLST delimiter is " + delimiter + " but these genes may violate the pattern and cause problems:"
                                      ^
SyntaxError: Missing parentheses in call to 'print'
Traceback (most recent call last):
  File "/usr/local/bin/srst2", line 9, in <module>
    load_entry_point('srst2==0.1.8', 'console_scripts', 'srst2')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/srst2/srst2.py", line 306
    print "Warning! MLST delimiter is " + delimiter + " but these genes may violate the pattern and cause problems:"
                                      ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by PWSmit** [comment]
downloading rather than cloning version 1.8  contained the right files.. solved. Sorry!

**Comment by stephenturner** [comment]
Should probably reopen this. The installation instructions call for a `git clone`, and for whatever reason, this script is not tracked/pushed, and build fails.

**Comment by katholt** [comment]
This occurred because this script was removed from the repo, but still referenced in setup.py.
This has now been fixed.
