### ISSUE TITLE
ValueError("Inputs must not be empty") when running srst2 invoking --input_pe

### ISSUE THREAD

**Issue by lilipeng** [katholt/srst2#74]
Hi,

I encounter the following error "ValueError("Inputs must not be empty.")" when I run the following command:

srst2 --output output_845354 --input_pe strain845354_1.fastq.gz strain845354_2.fastq.gz -mlst_db Staphylococcus_aureus.fasta --mlst_definitions saureus.txt --mlst_delimiter '_' --threads 16 --log --save_scores –read_type q

I run this in the command line in my UNIX terminal and get the following output (error message is at the end).  Does this issue have to do with the type of files being inputted as paired-end reads, or Python 2.7?

thank you,
Lili

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Attempting to read 7 loci from ST database paeruginosa.txt
Read ST database paeruginosa.txt successfully
2628368 reads; of these:
  2628368 (100.00%) were paired; of these:
    2626798 (99.94%) aligned concordantly 0 times
    11 (0.00%) aligned concordantly exactly 1 time
    1559 (0.06%) aligned concordantly >1 times
    ----
    2626798 pairs aligned concordantly 0 times; of these:
      0 (0.00%) aligned discordantly 1 time
    ----
    2626798 pairs aligned 0 times concordantly or discordantly; of these:
      5253596 mates make up the pairs; of these:
        5252629 (99.98%) aligned 0 times
        32 (0.00%) aligned exactly 1 time
        935 (0.02%) aligned >1 times
0.08% overall alignment rate
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
/home/pengx/.local/lib/python2.7/site-packages/scipy/stats/_discrete_distns.py:57: RuntimeWarning: floating point number truncated to an integer
  vals = special.bdtr(k, n, p)
Traceback (most recent call last):
  File "/rbxpkg/users/pengx/anaconda2/bin/srst2", line 11, in <module>
    load_entry_point('srst2==0.2.0', 'console_scripts', 'srst2')()
  File "/rbxpkg/users/pengx/anaconda2/lib/python2.7/site-packages/srst2/srst2.py", line 1717, in main
    mlst_report, mlst_results = run_srst2(args, fileSets, args.mlst_db, "mlst")
  File "/rbxpkg/users/pengx/anaconda2/lib/python2.7/site-packages/srst2/srst2.py", line 1264, in run_srst2
    db_results_list, fasta)
  File "/rbxpkg/users/pengx/anaconda2/lib/python2.7/site-packages/srst2/srst2.py", line 1327, in process_fasta_db
    results,gene_list, db_report, cluster_symbols, max_mismatch)
  File "/rbxpkg/users/pengx/anaconda2/lib/python2.7/site-packages/srst2/srst2.py", line 1429, in map_fileSet_to_db
    size_allele, next_to_del_depth_allele, run_type,unique_gene_symbols, unique_allele_symbols)
  File "/rbxpkg/users/pengx/anaconda2/lib/python2.7/site-packages/srst2/srst2.py", line 559, in score_alleles
    slope, _intercept, _r_value, _p_value, _std_err = linregress(exp_pvals2, pvals)
  File "/home/pengx/.local/lib/python2.7/site-packages/scipy/stats/_stats_mstats_common.py", line 72, in linregress
    raise ValueError("Inputs must not be empty.")
ValueError: Inputs must not be empty.

**Comment by amilesj** [comment]
Hi Lili,

I know it has been awhile since you posted this but just in case: I also ran into this error for a portion of my samples. In my case, it had something to do with (accidentally) using SAMtools v 1.3.1. When I fixed my SRST2_SAMTOOLS environmental variable to actually point to SAMtools v 0.1.18 (as recommended in the instructions), I no longer had this problem. 

Best,
Arianna
