### ISSUE TITLE
Reference file does not seem to be a FASTA file

### ISSUE THREAD

**Issue by bc2zb** [katholt/srst2#95]
I am trying to get srst2 to run on some illumina data, and using ARGannot.r1.fasta from the /data/ directory gives me the above error. I tried rerunning the command with ARGannot_r2.fasta as well, and get the same error. I installed srst2 via conda into a new environment. 

```
srst2 --input_pe ../R1_001.fastq.gz ../R2_001.fastq.gz --output pEG1-06_S1_L001_test --log --gene_db ARGannot.r1.fasta

```
Here's the output

```
Settings:
  Output files: "ARGannot.r1.fasta.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  ARGannot.r1.fasta
Building a SMALL index
Reading reference sizes
Warning: Encountered reference sequence with only gaps
Warning: Encountered empty reference sequence
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered empty reference sequence
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered empty reference sequence
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered empty reference sequence
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered empty reference sequence
  Time reading reference sizes: 00:00:00
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
Reference file does not seem to be a FASTA file
  Time to join reference sequences: 00:00:00
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 ARGannot.r1.fasta ARGannot.r1.fasta 
Deleting "ARGannot.r1.fasta.3.bt2" file written during aborted indexing attempt.
Deleting "ARGannot.r1.fasta.4.bt2" file written during aborted indexing attempt.
Deleting "ARGannot.r1.fasta.1.bt2" file written during aborted indexing attempt.
Deleting "ARGannot.r1.fasta.2.bt2" file written during aborted indexing attempt.
Traceback (most recent call last):
  File "../miniconda3/envs/srst2/bin/srst2", line 11, in <module>
    load_entry_point('srst2==0.2.0', 'console_scripts', 'srst2')()
  File "../miniconda3/envs/srst2/lib/python2.7/site-packages/srst2-0.2.0-py2.7.egg/srst2/srst2.py", line 1727, in main
  File "../miniconda3/envs/srst2/lib/python2.7/site-packages/srst2-0.2.0-py2.7.egg/srst2/srst2.py", line 155, in bowtie_index
  File "../miniconda3/envs/srst2/lib/python2.7/site-packages/srst2-0.2.0-py2.7.egg/srst2/srst2.py", line 143, in run_command
srst2.srst2.CommandError: {'message': "Command 'bowtie2-build ARGannot.r1.fasta ARGannot.r1.fasta' failed with non-zero exit status: 1"}
```

**Comment by katholt** [comment]
Are you providing the actual path to the fasta file? I.e. since in your command there is no path specified, is the fasta file in the directory from which you are running the command? If you do 'less ARGannot.r1.fasta' do you see the file and is it in fasta format?

**Comment by bc2zb** [comment]
I am indeed the fasta file is in the directory I am calling srst2 from. I found the issue by doing a less on the fasta, it was in html for some reason, I downloaded again, checked the contents, and it appears to be working fine now. Thanks for the prompt responses.
